DROP TABLE IF EXISTS bear;

CREATE TABLE IF NOT EXISTS bear (
    id VARCHAR(36) NOT NULL PRIMARY KEY, 
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    details TEXT
);
