// Code generated by goagen v1.6.2, DO NOT EDIT.
//
// API "BearSighting": Application Contexts
//
// Command:
// $ main

package app

import (
	"context"
	goa "github.com/shogo82148/goa-v1"
	"net/http"
)

// AddSightingsContext provides the sightings add action context.
type AddSightingsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *AddSightingsPayload
}

// NewAddSightingsContext parses the incoming request URL and body, performs validations and creates the
// context used by the sightings controller add action.
func NewAddSightingsContext(ctx context.Context, r *http.Request, service *goa.Service) (*AddSightingsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := AddSightingsContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// addSightingsPayload is the sightings add action payload.
type addSightingsPayload struct {
	// Specific area or district where the sighting occurred
	Area *string `form:"area,omitempty" json:"area,omitempty" yaml:"area,omitempty" xml:"area,omitempty"`
	// City or municipality of the sighting
	City *string `form:"city,omitempty" json:"city,omitempty" yaml:"city,omitempty" xml:"city,omitempty"`
	// Classification of sighting
	Classification *string `form:"classification,omitempty" json:"classification,omitempty" yaml:"classification,omitempty" xml:"classification,omitempty"`
	// Date of the sighting (ISO 8601 format)
	Date *string `form:"date,omitempty" json:"date,omitempty" yaml:"date,omitempty" xml:"date,omitempty"`
	// Additional details or description
	Details *string `form:"details,omitempty" json:"details,omitempty" yaml:"details,omitempty" xml:"details,omitempty"`
	// Latitude of the sighting location
	Latitude *float64 `form:"latitude,omitempty" json:"latitude,omitempty" yaml:"latitude,omitempty" xml:"latitude,omitempty"`
	// Longitude of the sighting location
	Longitude *float64 `form:"longitude,omitempty" json:"longitude,omitempty" yaml:"longitude,omitempty" xml:"longitude,omitempty"`
	// Details about the sighting situation
	Situation *string `form:"situation,omitempty" json:"situation,omitempty" yaml:"situation,omitempty" xml:"situation,omitempty"`
	// Time of the sighting (24-hour format HH:MM)
	Time *string `form:"time,omitempty" json:"time,omitempty" yaml:"time,omitempty" xml:"time,omitempty"`
}

// Validate runs the validation rules defined in the design.
func (payload *addSightingsPayload) Validate() (err error) {
	if payload.Latitude == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "latitude"))
	}
	if payload.Longitude == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "longitude"))
	}
	if payload.City == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "city"))
	}
	if payload.Area == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "area"))
	}
	if payload.Date == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "date"))
	}
	if payload.Time == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "time"))
	}
	if payload.Situation == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "situation"))
	}
	if payload.Classification == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "classification"))
	}
	if payload.Classification != nil {
		if !(*payload.Classification == "目撃" || *payload.Classification == "痕跡" || *payload.Classification == "噂") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError(`raw.classification`, *payload.Classification, []interface{}{"目撃", "痕跡", "噂"}))
		}
	}
	return
}

// Publicize creates AddSightingsPayload from addSightingsPayload
func (payload *addSightingsPayload) Publicize() *AddSightingsPayload {
	var pub AddSightingsPayload
	if payload.Area != nil {
		pub.Area = *payload.Area
	}
	if payload.City != nil {
		pub.City = *payload.City
	}
	if payload.Classification != nil {
		pub.Classification = *payload.Classification
	}
	if payload.Date != nil {
		pub.Date = *payload.Date
	}
	if payload.Details != nil {
		pub.Details = payload.Details
	}
	if payload.Latitude != nil {
		pub.Latitude = *payload.Latitude
	}
	if payload.Longitude != nil {
		pub.Longitude = *payload.Longitude
	}
	if payload.Situation != nil {
		pub.Situation = *payload.Situation
	}
	if payload.Time != nil {
		pub.Time = *payload.Time
	}
	return &pub
}

// AddSightingsPayload is the sightings add action payload.
type AddSightingsPayload struct {
	// Specific area or district where the sighting occurred
	Area string `form:"area" json:"area" yaml:"area" xml:"area"`
	// City or municipality of the sighting
	City string `form:"city" json:"city" yaml:"city" xml:"city"`
	// Classification of sighting
	Classification string `form:"classification" json:"classification" yaml:"classification" xml:"classification"`
	// Date of the sighting (ISO 8601 format)
	Date string `form:"date" json:"date" yaml:"date" xml:"date"`
	// Additional details or description
	Details *string `form:"details,omitempty" json:"details,omitempty" yaml:"details,omitempty" xml:"details,omitempty"`
	// Latitude of the sighting location
	Latitude float64 `form:"latitude" json:"latitude" yaml:"latitude" xml:"latitude"`
	// Longitude of the sighting location
	Longitude float64 `form:"longitude" json:"longitude" yaml:"longitude" xml:"longitude"`
	// Details about the sighting situation
	Situation string `form:"situation" json:"situation" yaml:"situation" xml:"situation"`
	// Time of the sighting (24-hour format HH:MM)
	Time string `form:"time" json:"time" yaml:"time" xml:"time"`
}

// Validate runs the validation rules defined in the design.
func (payload *AddSightingsPayload) Validate() (err error) {

	if !(payload.Classification == "目撃" || payload.Classification == "痕跡" || payload.Classification == "噂") {
		err = goa.MergeErrors(err, goa.InvalidEnumValueError(`raw.classification`, payload.Classification, []interface{}{"目撃", "痕跡", "噂"}))
	}
	return
}

// Created sends a HTTP response with status code 201.
func (ctx *AddSightingsContext) Created(r *Sighting) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 201, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *AddSightingsContext) BadRequest() error {
	ctx.ResponseData.WriteHeader(400)
	return nil
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *AddSightingsContext) InternalServerError() error {
	ctx.ResponseData.WriteHeader(500)
	return nil
}
