// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package webapi

import (
	"backend/app/datastore/mysql"
	"backend/app/interactor"
	"backend/database"
	"backend/webapi/app"
	"github.com/google/wire"
	"github.com/shogo82148/goa-v1"
)

// Injectors from wire.go:

// InitializeBearController は BearController の依存関係を初期化します。
func InitializeBearController(service *goa.Service) (*BearController, error) {
	config := mysql.NewMySQLConfig()
	db, err := mysql.New(config)
	if err != nil {
		return nil, err
	}
	bearCreater := mysql.NewBearCreator()
	bearCreatorConfig := &interactor.BearCreatorConfig{
		TxBeginner:  db,
		BearCreator: bearCreater,
	}
	interactorBearCreater := interactor.NewBearCreater(bearCreatorConfig)
	bearController := NewBearController(service, interactorBearCreater)
	return bearController, nil
}

// wire.go:

// WireSet は webapi の依存性を解決するための Wire セット
var WireSet = wire.NewSet(database.NewDB, mysql.NewMySQLConfig, interactor.ConsoleSet, mysql.Set, NewBearController, wire.Bind(new(app.BearController), new(*BearController)))
