// Code generated by goagen v1.6.2, DO NOT EDIT.
//
// API "BearSighting": Application Media Types
//
// Command:
// $ main

package app

// クマ目撃情報 (default view)
//
// Identifier: application/vnd.sighting+json; view=default
type Sighting struct {
	// 目撃場所の具体的な住所
	Address string `form:"address" json:"address" yaml:"address" xml:"address"`
	// 目撃があった市区町村
	City string `form:"city" json:"city" yaml:"city" xml:"city"`
	// 目撃日
	Date string `form:"date" json:"date" yaml:"date" xml:"date"`
	// 目撃の追加詳細や説明
	Details string `form:"details" json:"details" yaml:"details" xml:"details"`
	// 一意の目撃情報ID
	ID string `form:"id" json:"id" yaml:"id" xml:"id"`
	// 目撃場所の緯度
	Latitude float64 `form:"latitude" json:"latitude" yaml:"latitude" xml:"latitude"`
	// 目撃場所の経度
	Longitude float64 `form:"longitude" json:"longitude" yaml:"longitude" xml:"longitude"`
	// 目撃時刻
	Time string `form:"time" json:"time" yaml:"time" xml:"time"`
}

// Validate validates the Sighting media type instance.
func (mt *Sighting) Validate() (err error) {

	return
}
