// Code generated by goagen v1.6.2, DO NOT EDIT.
//
// API "BearSighting": Application Media Types
//
// Command:
// $ main

package app

// Bear Sighting (default view)
//
// Identifier: application/vnd.sighting+json; view=default
type Sighting struct {
	// Specific area or district where the sighting occurred
	Area string `form:"area" json:"area" yaml:"area" xml:"area"`
	// City or municipality of the sighting
	City string `form:"city" json:"city" yaml:"city" xml:"city"`
	// Classification of sighting
	Classification string `form:"classification" json:"classification" yaml:"classification" xml:"classification"`
	// Date of the sighting
	Date string `form:"date" json:"date" yaml:"date" xml:"date"`
	// Additional details or description
	Details *string `form:"details,omitempty" json:"details,omitempty" yaml:"details,omitempty" xml:"details,omitempty"`
	// Unique sighting ID
	ID int `form:"id" json:"id" yaml:"id" xml:"id"`
	// Latitude of the sighting location
	Latitude float64 `form:"latitude" json:"latitude" yaml:"latitude" xml:"latitude"`
	// Longitude of the sighting location
	Longitude float64 `form:"longitude" json:"longitude" yaml:"longitude" xml:"longitude"`
	// Details about the sighting situation
	Situation string `form:"situation" json:"situation" yaml:"situation" xml:"situation"`
	// Time of the sighting
	Time string `form:"time" json:"time" yaml:"time" xml:"time"`
}

// Validate validates the Sighting media type instance.
func (mt *Sighting) Validate() (err error) {

	return
}
